// 100 句雙語閱讀題庫 (sentences_100.js)
window.sentences100Data = [
  { id: 1, english: "It would be dangerous to drink two bottles of whiskey and drive a car.", chinese: "喝兩瓶威士忌還開車是很危險的。" },
  { id: 2, english: "It is very dangerous to cross a busy street before the light turns green.", chinese: "在燈號變綠之前橫穿交通繁忙的街道是非常危險的。" },
  { id: 3, english: "It is really pleasant to take a walk early in the morning, listening to birds sing.", chinese: "一大清早一邊聽著鳥鳴一邊散步，真是一件愉快的事。" },
  { id: 4, english: "Most Japanese high school students go to a cram school to prepare for college entrance exams.", chinese: "多數日本高中生都會去補習班準備大學入學考試。" },
  { id: 5, english: "When waiting for the elevator to come or the traffic light to change, most Japanese people become irritated in only thirty seconds.", chinese: "日本人只要在等電梯或等紅燈時，短短三十秒就會開始感到煩躁。" },
  { id: 6, english: "An elderly woman sitting next to me on the train asked me where I was going.", chinese: "火車上坐在我旁邊的一位老太太問我要去哪裡。" },
  { id: 7, english: "Tom told us that we should rent a car to get around the city because the public transportation was inconvenient.", chinese: "湯姆告訴我們，因為大眾運輸很不方便，所以我們應該租輛車在城裡四處逛逛。" },
  { id: 8, english: "Everyone should be free to decide when to get married and whether to have children.", chinese: "每個人都應該有權自由決定何時結婚以及是否要生孩子。" },
  { id: 9, english: "It is impossible to predict where and when there will be a major earthquake.", chinese: "大地震何時何地會發生是無法預測的。" },
  { id: 10, english: "Tom insisted that everything would be all right, but I couldn't help feeling worried.", chinese: "湯姆堅持說一切都會沒問題的，但我還是忍不住感到擔心。" },
  { id: 11, english: "It never occurred to me that my remark might hurt her feelings.", chinese: "我從沒想過我的話會傷害到她的感情。" },
  { id: 12, english: "\"Tom, dinner is ready.\" \"OK, mom. I'm coming.\"", chinese: "「湯姆，晚餐好了。」「好，媽媽，我馬上來。」" },
  { id: 13, english: "I'll call you when I get to Narita Airport.", chinese: "我一到成田機場就會打電話給你。" },
  { id: 14, english: "If you take the train to Tokyo Disneyland from here, you have to change three times.", chinese: "如果你從這裡坐火車去東京迪士尼樂園，你必須轉車三次。" },
  { id: 15, english: "I've decided to look for a job abroad when I graduate from college.", chinese: "我決定大學畢業後要到國外找工作。" },
  { id: 16, english: "This dryer doesn't work. Something seems to be wrong with it.", chinese: "這台吹風機不會動了。它好像有些故障。" },
  { id: 17, english: "The best thing about my stay with an American family was that the parents treated me just like their daughter.", chinese: "我在美國寄宿家庭生活最棒的一點是，父母把我就像親生女兒一般對待。" },
  { id: 18, english: "I lived in Canada for three years when I was in my teens because my father was transferred there.", chinese: "我十幾歲時因為父親被調派到那裡，曾在加拿大住了三年。" },
  { id: 19, english: "The internet is widely used, so sales of personal computers have been rapidly increasing over the last few years.", chinese: "網際網路被廣泛使用，因此個人電腦的銷量在過去幾年裡急速增長。" },
  { id: 20, english: "I've often heard Tom boast that he is very good at swimming, but I've never actually seen him swim.", chinese: "我經常聽湯姆吹噓說他游泳很厲害，但我從未真正見過他游泳。" },
  { id: 21, english: "It has been only a week since I began a part-time job at a convenient store, but I'm already used to it.", chinese: "我在便利商店打工才一個禮拜，但已經習慣了。" },
  { id: 22, english: "When I got on the train this morning, I couldn't find an empty seat.", chinese: "我今天早上上車時，找不到一個空位。" },
  { id: 23, english: "I'm not wearing glasses now, so I can't make out what the sign says.", chinese: "我現在沒戴眼鏡，所以看不清標誌上寫的是什麼。" },
  { id: 24, english: "Less than twenty-four hours after I return to my hometown, without realizing it, I start to talk in the local dialect.", chinese: "我回到家鄉不到二十四小時，不知不覺就開始講起當地方言。" },
  { id: 25, english: "Humans learn to express what they think by the age of five or six.", chinese: "人類在五、六歲時就學會表達自己的想法。" },
  { id: 26, english: "Thanks to the map you drew me the other day, I managed to get here without lost.", chinese: "多虧你前幾天畫給我的地圖，我才能沒有迷路地來到這裡。" },
  { id: 27, english: "Last summer I took two weeks off, and went on a trip to Europe with my wife.", chinese: "去年夏天我請了兩週的假，和妻子去歐洲旅行。" },
  { id: 28, english: "Bob had changed a lot, so when I saw him at a class reunion, I didn't recognize him.", chinese: "鮑伯變了很多，所以在同學會上看到他時，我沒認出他來。" },
  { id: 29, english: "When I visited my hometown for the first time in twenty years, I found that it was no longer what it was used to be.", chinese: "當我二十年來第一次訪問家鄉時，我發現它已經不再是過去那個樣子了。" },
  { id: 30, english: "I stayed up till four last night preparing for the math lesson, so I feel very sleepy.", chinese: "我昨晚為了準備數學課熬夜到四點，所以現在覺得很困。" },
  { id: 31, english: "I've finished reading the novel I borrowed from the library yesterday, so now I have nothing to do.", chinese: "我已經讀完了昨天從圖書館借的小說，所以現在沒事可做。" },
  { id: 32, english: "If you had taken this medicine and stayed in bed, you would probably have got well in two or three days.", chinese: "如果你吃了這藥並好好躺著休息，大概兩三天就會康復了。" },
  { id: 33, english: "The teacher says that we should stay here for a while because if we left now, we might get caught in a thunderstorm on the way.", chinese: "老師說我們應該在這裡待一會兒，因為如果現在離開，半路上可能會遇到雷雨。" },
  { id: 34, english: "People wish they could live forever and never become older. However, if this wish came true, there would be too many people on the earth.", chinese: "人們希望能夠長生不老且永不變老。然而，如果這個願望成真，地球上的人就會太多了。" },
  { id: 35, english: "Ann looks happy. Something good must have happened to her.", chinese: "安看起來很高興。她身上一定發生了什麼好事。" },
  { id: 36, english: "If you have been to old European cities, you must have been impressed by the beautiful streets.", chinese: "如果你去過歐洲的古老城市，你一定會對那美麗的街道印象深刻。" },
  { id: 37, english: "Without fossil fuels such as oil or coal, the history of the 20th century would have been completely different.", chinese: "如果沒有石油或煤炭等化石燃料，20世紀的歷史將完全不同。" },
  { id: 38, english: "Some students coming to the library act as if they are in a coffee shop.", chinese: "有些來到圖書館的學生表現得好像身處咖啡廳一樣。" },
  { id: 39, english: "When I was a child, I often wished my house were a little larger.", chinese: "小時候，我常常希望自己的家能再大一點。" },
  { id: 40, english: "I'd like to work as a volunteer helping victims of natural disasters, such as floods or earthquakes.", chinese: "我想擔任志工，去幫助洪水或地震等自然災害的災民。" },
  { id: 41, english: "Tom has nice drums, and he never lets anyone else play them.", chinese: "湯姆有一套很好的爵士鼓，他絕不讓別人碰。" },
  { id: 42, english: "At first I thought Tom was joking, but later I realized he was serious.", chinese: "起初我以為湯姆在開玩笑，但後來我發現他是認真的。" },
  { id: 43, english: "Last Sunday I tried making Italian food for the first time, and it was delicious.", chinese: "上週日我第一次嘗試做義大利料理，結果非常好吃。" },
  { id: 44, english: "Some people say that they don't like summer because it is so hot that they don't feel like doing anything. However, I like the heat of summer because I can swim in the sea.", chinese: "有人說他們討厭夏天，因為天氣太熱什麼都不想做。不過，我喜歡夏天的炎熱，因為可以在海裡游泳。" },
  { id: 45, english: "James came to Japan eight years ago not only because he wanted to visit temples, but also because he had a Japanese girlfriend.", chinese: "詹姆斯八年前來到日本，不僅是因為想參觀寺廟，還因為他有一個日本女朋友。" },
  { id: 46, english: "I am against human cloning. That is because it could cause duplication of dictators.", chinese: "我反對複製人。那是由於這可能會導致獨裁者的複製。" },
  { id: 47, english: "The graph shows that in Japan the birth rate has been decreasing since 1985. This decrease is partly because it costs a lot of money to raise children.", chinese: "圖表顯示，日本的出生率自1985年以來一直在下降。這種下降部分是因為養育孩子需要花很多錢。" },
  { id: 48, english: "I apologized to Ann for being late, but she didn't forgive me.", chinese: "我為遲到向安道歉，但她沒有原諒我。" },
  { id: 49, english: "During the math class, my cell phone began to ring, and the teacher severely scolded me. I regretted that I hadn't turned it off.", chinese: "上數學課時，我的手機響了，老師狠狠地訓斥了我。我很後悔沒有把它關機。" },
  { id: 50, english: "I'm so busy doing the housework every day that I have no time to see a movie.", chinese: "我每天忙著做家事，連看電影的時間都沒有。" },
  { id: 51, english: "This wooden desk is too heavy for me to carry upstairs alone.", chinese: "這張木製書桌太重了，我一個人搬不上二樓。" },
  { id: 52, english: "While traveling in Europe, I was disappointed that wherever I went, there were many Japanese tourists.", chinese: "在歐洲旅行時，令我失望的是，無論走到哪裡都有很多日本遊客。" },
  { id: 53, english: "I was very happy when I saw my mother going to work wearing the earrings I had bought her.", chinese: "看到媽媽戴著我買給她的耳環去上班，我非常高興。" },
  { id: 54, english: "If you expect that schools only teach academic subjects, then this proves that you don't understand what schools are for.", chinese: "如果你認為學校只教導學術科目，這就證明你並不了解學校的真正目的。" },
  { id: 55, english: "Most Japanese people spend most of their time working to live.", chinese: "大多數日本人都把大部分的時間花在為了生計而工作上。" },
  { id: 56, english: "Japanese people usually express their feelings as indirectly as possible so that they won't offend others.", chinese: "為了不冒犯他人，日本人通常會盡可能間接地表達自己的感受。" },
  { id: 57, english: "Whether a college is good or bad depends not only on how many books its library has and how good they are. It also depends on how intelligent its teachers and students are.", chinese: "一所大學的好壞不僅取決於其圖書館有多少藏書及其品質，也取決於其師生的素質。" },
  { id: 58, english: "The increase in the amount of CO2 in the atmosphere is closely connected with global warming.", chinese: "大氣中二氧化碳含量的增加與全球暖化息息相關。" },
  { id: 59, english: "The more modern civilization advances, the longer we are forced to stay up at night, and the less sleep we get.", chinese: "現代文明越進步，我們被迫熬夜的時間就越長，得到的睡眠就越少。" },
  { id: 60, english: "Doctors and teachers are alike in that both of them deal not with things but with people.", chinese: "醫生和教師的相似之處在於，他們打交道的都不是物品，而是人。" },
  { id: 61, english: "Professional baseball is far more exciting at a stadium than on TV.", chinese: "在球場看職業棒球比在電視上看刺激得多。" },
  { id: 62, english: "This motorbike is about twice as expensive in the U.K. as in Japan.", chinese: "這輛機車在英國的價格大約是日本的兩倍。" },
  { id: 63, english: "Just because young people today read less than they used to, it doesn't always follow that they are less eager to learn.", chinese: "不能因為現在的年輕人比以前讀的書少，就必然得出他們求知慾較弱的結論。" },
  { id: 64, english: "Frankly speaking, the entrance exams I took yesterday were far more difficult than I had expected.", chinese: "坦白說，我昨天考的入學考試比我預期的要難得多。" },
  { id: 65, english: "A lot of people have personal computers, but very few of them know how to use them effectively.", chinese: "很多人都有個人電腦，但極少有人知道如何有效地使用它們。" },
  { id: 66, english: "A lot of housewives complain that prices are too high.", chinese: "很多家庭主婦抱怨物價太高。" },
  { id: 67, english: "In some countries people have too much food, while in others tens of thousands of children are starving.", chinese: "在某些國家，人們擁有過剩的食物，而在其他國家，成千上萬的兒童卻在捱餓。" },
  { id: 68, english: "Don't forget to turn off the air conditioner before you go to bed, or you'll catch a cold.", chinese: "睡覺前別忘了關空調，否則你會感冒的。" },
  { id: 69, english: "There is a saying that a cold can cause a variety of diseases. Take care not to catch a cold.", chinese: "俗話說感冒會引發各種疾病。注意別感冒了。" },
  { id: 70, english: "On the Internet, you can exchange thoughts and ideas with people all over the world, regardless of their age, sex, or nationality.", chinese: "在網路上，你可以與世界各地的人交換想法和觀點，無論他們的年齡、性別或國籍為何。" },
  { id: 71, english: "However much exercise you get, you won't lose weight unless you count your calories.", chinese: "不管你做多少運動，如果不計算卡路里，你是瘦不下來的。" },
  { id: 72, english: "Although you believe you know a word, you may learn something new if you look it up in the dictionary.", chinese: "儘管你認為自己認識一個單字，但如果你去查字典，可能還是會學到新的東西。" },
  { id: 73, english: "Some Japanese tourists lack common sense and carry a lot of cash in their backpockets.", chinese: "有些日本遊客缺乏常識，把大量現金放在褲子後口袋裡。" },
  { id: 74, english: "In order to stay healthy, you should have a balanced diet and get regular exercise.", chinese: "為了保持健康，你應該飲食均衡並進行規律運動。" },
  { id: 75, english: "If you live in a developing country for a while, you have an opportunity to look at Japan from a different point of view.", chinese: "如果你在發展中國家住上一段時間，你就會有機會從不同的角度來審視日本。" },
  { id: 76, english: "It is not until you go abroad that you realize how many neon lights there are in big Japanese cities.", chinese: "直到你出了國，才會發覺日本大都市的霓虹燈有多麼多。" },
  { id: 77, english: "It is a pity that many Japanese people mistakenly believe that they have only to speak English to be internationally-minded.", chinese: "很遺憾，許多日本人誤以為只要會講英語就能具備國際視野。" },
  { id: 78, english: "It is surprising that many Americans don't care how you pronounce English as long as they can understand what you are trying to say.", chinese: "令人驚訝的是，只要能聽懂你要表達的意思，許多美國人並不在乎你英語發音得好不好。" },
  { id: 79, english: "The best things you can do to protect nature are to reduce garbage and to use environmentally friendly products.", chinese: "為了保護自然，你能做的最好的事情就是減少垃圾並使用環保產品。" },
  { id: 80, english: "It is said that seven out of ten young Japanese people don't believe in religion.", chinese: "據說十個日本年輕人中有七個沒有宗教信仰。" },
  { id: 81, english: "Ways of greeting vary from country to country. In Japan bowing is more common than shaking hands.", chinese: "各國的問候方式各不相同。在日本，鞠躬比握手更常見。" },
  { id: 82, english: "Hamamatsu is located east of Lake Hamana, which if famous for its beautiful scenery and delicious fish.", chinese: "濱松位於濱名湖以東，該湖以美麗的風景和美味的魚類而聞名。" },
  { id: 83, english: "Quite a few elderly women look down on their hasbands, who cannot do naything by themselves and ask too much of them.", chinese: "有不少老年女性看不起自己的丈夫，因為他們什麼事都自己不會做，還對妻子要求過多。" },
  { id: 84, english: "The movie theater is about twenty minutes' walk from here, but it takes only five minutes to get there by subway.", chinese: "那家電影院從這裡步行大約二十分鐘，但如果坐地鐵只需五分鐘就能到達。" },
  { id: 85, english: "It cost ten thousanf yen to have this bile repaired.", chinese: "請人修理這輛腳踏車花了一萬日圓。" },
  { id: 86, english: "There are four in my family. Our apartment is on the fifth floor of this building.", chinese: "我家有四口人。我們的公寓在這棟建築物的五樓。" },
  { id: 87, english: "The tendency for young people to belive everything that is printed is nothing new.", chinese: "年輕人對鉛字印刷品深信不疑的傾向並不是什麼新鮮事。" },
  { id: 88, english: "When I was studying in Paris, a famous painter bought me a meal at a first-class restaurant.", chinese: "我在巴黎留學時，一位著名的畫家請我在一流餐廳吃了一頓飯。" },
  { id: 89, english: "Tom finally realized his dream of becoming an astronaut, but at the expense of many other things.", chinese: "湯姆終於實現了成為太空人的夢想，但代價是犧牲了許多其他的事物。" },
  { id: 90, english: "If city life gives you stress and fatigue, it is best to relax in the mountains or in beaches in order to relieve them.", chinese: "如果都市生活帶給你壓力和疲勞，最好到山裡或海灘放鬆一下以消除它們。" },
  { id: 91, english: "In Japan, women have difficulty getting promoted or returning to their jobs after giving birth and raising their children.", chinese: "在日本，女性在生完孩子並撫養長大後，要在升遷或重返職場方面面臨困難。" },
  { id: 92, english: "In the U.S., parents drive their children everywhere until they are old enough to get a driver's license.", chinese: "在美國，父母會開車載著孩子去任何地方，直到他們長到足以考取駕照的年齡。" },
  { id: 93, english: "\"Excuse me. Could you tell me how to get to the post office?\" \"Go straight for two blocks, then turn left. You'll find it on your right.\"", chinese: "「打擾一下，請問去郵局怎麼走？」「直走兩個街區，然後左轉。它就在你的右邊。」" },
  { id: 94, english: "\"What do you think of our new teacher?\" \"There is something about her that attracts me.\"", chinese: "「你覺得我們的新老師怎麼樣？」「她身上有一種吸引我的特質。」" },
  { id: 95, english: "People who don't feel guilty about occupying two seats on a crowded train really make me angry.", chinese: "在擁擠的火車上佔用兩個座位卻一點也不覺得內疚的人，真讓人火大。" },
  { id: 96, english: "Everyone is born with a talent. The question is whether they can find it or not.", chinese: "每個人生來都有某種天賦。問題在於他們能否找到它。" },
  { id: 97, english: "When I left the office for lunch, I ran into an old friend from high school.", chinese: "我離開辦公室去吃午餐時，碰到了高中時的老朋友。" },
  { id: 98, english: "This music is worth listening to over and over again. I recommend it.", chinese: "這首音樂值得一聽再聽。我很推薦。" },
  { id: 99, english: "I've finished reading the novel I borrowed from the library yesterday, so now I have nothing to do.", chinese: "我已經讀完了昨天從圖書館借的小說，所以現在沒事可做。" },
  { id: 100, english: "Tom insisted that everything would be all right, but I couldn't help feeling worried.", chinese: "湯姆堅持說一切都會沒問題的，但我還是忍不住感到擔心。" }
];